version: "3"
services:
  web:
    container_name: ezlunch-backend
    build: .
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
